### ISSUE TITLE
Add some good learning ressources, tutorials, best practises..

### ISSUE THREAD

**Issue by mpathy** [busterc/awesome-cordova#8]
Hi there..

I am used to from the other awesome lists, that there is a good selection for learning material, and things to read and watch, out of experiences from the people who felt capable to create such a list.

I would be really happy, in the spirit of the original lists, that you provide us with some links to stuff that you find useful over the time.

**Comment by busterc** [comment]
Thanks for the suggestion. I created a Learning section and included the official create your first cordova app link. Hopefully others will PR some great resources; personally I've never seen or read great learning materials, it's a definite soft spot for the cordova project imho.
